import {
  Sandwich,
  LayoutDashboard,
  ListTodo,
  MessageCircle,
  ClipboardList,
  FolderOpen,
  BarChart3,
  Users,
  Car,
  Building2,
  Building,
  FileText,
  Settings,
  Sheet,
  Lightbulb,
  Inbox,
  Hash,
  Scale,
  Calendar,
  MapPin,
  Route,
  Clock,
  Gift,
  Link,
  Calculator,
  Truck,
  UserCog,
  Trophy,
  FileSpreadsheet,
  Package,
  HelpCircle,
  StickyNote,
  Image,
  DollarSign,
  Receipt,
} from 'lucide-react';
import { NavItem } from './nav.types';
import { PERMISSIONS } from '@shared/auth-utils';
import sandwich_logo from '@assets/LOGOS/sandwich logo.png';

export const NAV_ITEMS: NavItem[] = [
  // DASHBOARD (at the very top)
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    href: 'dashboard',
    group: 'dashboard',
  },

  // MY ACTIONS - Personal dashboard for user assignments
  {
    id: 'my-actions',
    label: 'My Actions',
    icon: ListTodo,
    href: 'my-actions',
    permission: PERMISSIONS.NAV_MY_ACTIONS,
    group: 'dashboard',
  },

  // AVAILABILITY
  {
    id: 'my-availability',
    label: 'My Availability',
    icon: Calendar,
    href: 'my-availability',
    permission: PERMISSIONS.NAV_MY_AVAILABILITY,
    group: 'dashboard',
  },
  {
    id: 'team-availability',
    label: 'Team Availability',
    icon: Users,
    href: 'team-availability',
    permission: PERMISSIONS.NAV_TEAM_AVAILABILITY,
    group: 'dashboard',
  },
  {
    id: 'google-calendar-availability',
    label: 'Volunteer Calendar',
    icon: Calendar,
    href: 'google-calendar-availability',
    permission: PERMISSIONS.NAV_VOLUNTEER_CALENDAR,
    group: 'dashboard',
    highlighted: true,
  },

  // COLLECTIONS LOG
  {
    id: 'collections',
    label: 'Collections Log',
    customIcon: sandwich_logo,
    href: 'collections',
    permission: PERMISSIONS.NAV_COLLECTIONS_LOG,
    group: 'collections',
    highlighted: true,
  },

  // Move these back to their original groups without creating "core"

  // COMMUNICATION
  {
    id: 'chat',
    label: 'Team Chat',
    icon: Hash,
    href: 'chat',
    permission: PERMISSIONS.NAV_TEAM_CHAT,
    group: 'communication',
  },
  {
    id: 'gmail-inbox',
    label: 'Inbox',
    icon: Inbox,
    href: 'gmail-inbox',
    permission: PERMISSIONS.NAV_INBOX,
    group: 'communication',
  },
  {
    id: 'suggestions',
    label: 'Suggestions',
    icon: Lightbulb,
    href: 'suggestions',
    permission: PERMISSIONS.NAV_SUGGESTIONS,
    group: 'communication',
  },
  {
    id: 'team-board',
    label: 'Team Board',
    icon: StickyNote,
    href: 'team-board',
    group: 'communication',
    highlighted: true,
  },
  {
    id: 'promotion',
    label: 'Promotion',
    icon: Image,
    href: 'promotion',
    group: 'communication',
  },

  // OPERATIONS (the weekly flow)
  {
    id: 'hosts',
    label: 'Hosts',
    icon: Building2,
    href: 'hosts',
    permission: PERMISSIONS.NAV_HOSTS,
    group: 'operations',
  },
  {
    id: 'drivers',
    label: 'Drivers',
    icon: Car,
    href: 'drivers',
    permission: PERMISSIONS.NAV_DRIVERS,
    group: 'operations',
  },
  {
    id: 'volunteers',
    label: 'Volunteers',
    icon: Users,
    href: 'volunteers',
    permission: PERMISSIONS.NAV_VOLUNTEERS,
    group: 'operations',
  },
  {
    id: 'recipients',
    label: 'Recipients',
    icon: Users,
    href: 'recipients',
    permission: PERMISSIONS.NAV_RECIPIENTS,
    group: 'operations',
  },
  {
    id: 'groups-catalog',
    label: 'Groups Catalog',
    icon: Building,
    href: 'groups-catalog',
    permission: PERMISSIONS.NAV_GROUPS_CATALOG,
    group: 'operations',
    highlighted: true,
  },
  {
    id: 'donation-tracking',
    label: 'Distribution Tracking',
    icon: Truck,
    href: 'donation-tracking',
    permission: PERMISSIONS.NAV_DISTRIBUTION_TRACKING,
    group: 'operations',
  },
  {
    id: 'inventory-calculator',
    label: 'Inventory Calculator',
    icon: Calculator,
    href: 'inventory-calculator',
    permission: PERMISSIONS.NAV_INVENTORY_CALCULATOR,
    group: 'operations',
  },
  {
    id: 'work-log',
    label: 'Work Log',
    icon: ClipboardList,
    href: 'work-log',
    permission: PERMISSIONS.NAV_WORK_LOG,
    group: 'operations',
  },
  {
    id: 'expenses',
    label: 'Expenses & Receipts',
    icon: Receipt,
    href: 'expenses',
    group: 'operations',
    highlighted: true,
  },

  // PLANNING & COORDINATION
  {
    id: 'event-requests',
    label: 'Event Requests',
    icon: Calendar,
    href: 'event-requests',
    permission: PERMISSIONS.NAV_EVENT_PLANNING,
    group: 'planning',
    highlighted: true,
  },
  {
    id: 'historical-import',
    label: 'Historical Import',
    icon: FileSpreadsheet,
    href: 'historical-import',
    permission: PERMISSIONS.DATA_IMPORT,
    group: 'planning',
  },
  {
    id: 'events',
    label: 'Events Google Sheet',
    icon: Sheet,
    href: 'events',
    permission: PERMISSIONS.EVENT_REQUESTS_VIEW,
    group: 'planning',
  },
  {
    id: 'signup-genius',
    label: 'Sign Up Genius',
    icon: Link,
    href: 'signup-genius',
    permission: PERMISSIONS.EVENT_REQUESTS_VIEW,
    group: 'planning',
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: ListTodo,
    href: 'projects',
    permission: PERMISSIONS.PROJECTS_VIEW,
    group: 'planning',
  },
  {
    id: 'meetings',
    label: 'Meetings',
    icon: ClipboardList,
    href: 'meetings',
    permission: PERMISSIONS.MEETINGS_VIEW,
    group: 'planning',
    highlighted: true,
  },
  {
    id: 'event-reminders',
    label: 'Event Reminders',
    icon: Clock,
    href: 'event-reminders',
    permission: PERMISSIONS.EVENT_REQUESTS_VIEW,
    group: 'planning',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    icon: BarChart3,
    href: 'analytics',
    permission: PERMISSIONS.ANALYTICS_VIEW,
    group: 'planning',
  },
  {
    id: 'grant-metrics',
    label: 'Grant Metrics',
    icon: Trophy,
    href: 'grant-metrics',
    permission: PERMISSIONS.NAV_GRANT_METRICS,
    group: 'planning',
  },
  {
    id: 'weekly-monitoring',
    label: 'Weekly Monitoring',
    icon: Clock,
    href: 'weekly-monitoring',
    permission: PERMISSIONS.NAV_WEEKLY_MONITORING,
    group: 'planning',
  },

  // DOCUMENTATION
  {
    id: 'resources',
    label: 'Resources',
    icon: FileText,
    href: 'resources',
    group: 'documentation',
    highlighted: true,
  },
  {
    id: 'quick-tools',
    label: 'Quick Tools',
    icon: Link,
    href: 'important-links',
    group: 'documentation',
  },
  {
    id: 'wishlist',
    label: 'Amazon Wishlist',
    icon: Gift,
    href: 'wishlist',
    permission: PERMISSIONS.NAV_WISHLIST,
    group: 'documentation',
  },
  {
    id: 'cooler-tracking',
    label: 'Cooler Tracking',
    icon: Package,
    href: 'cooler-tracking',
    permission: PERMISSIONS.NAV_COOLER_TRACKING,
    group: 'operations',
  },
  {
    id: 'document-management',
    label: 'Document Management',
    icon: FileText,
    href: 'document-management',
    permission: PERMISSIONS.NAV_DOCUMENT_MANAGEMENT,
    group: 'documentation',
  },

  // ADMIN
  {
    id: 'admin',
    label: 'Admin Panel',
    icon: Settings,
    href: 'admin',
    permission: PERMISSIONS.ADMIN_PANEL_ACCESS,
    group: 'admin',
  },
  {
    id: 'user-management',
    label: 'User Management',
    icon: UserCog,
    href: 'user-management',
    permission: PERMISSIONS.ADMIN_PANEL_ACCESS,
    group: 'admin',
  },

  // HELP - Always at the bottom (standard UX pattern)
  {
    id: 'help',
    label: 'Help',
    icon: HelpCircle,
    href: 'help',
    permission: PERMISSIONS.NAV_HELP,
    group: 'help',
  },
];