import {
  Sandwich,
  LayoutDashboard,
  ListTodo,
  MessageCircle,
  ClipboardList,
  FolderOpen,
  BarChart3,
  Users,
  Car,
  Building2,
  Building,
  FileText,
  Settings,
  Sheet,
  Lightbulb,
  Inbox,
  Hash,
  Scale,
  Calendar,
  MapPin,
  Route,
  Clock,
  Gift,
  Link,
  Calculator,
  Truck,
  UserCog,
} from 'lucide-react';
import { NavItem } from './nav.types';
import { PERMISSIONS } from '@shared/auth-utils';
import sandwich_logo from '@assets/LOGOS/sandwich logo.png';

export const NAV_ITEMS: NavItem[] = [
  // DASHBOARD (at the very top)
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    href: 'dashboard',
    group: 'dashboard',
  },

  // MY ACTIONS - Personal dashboard for user assignments
  {
    id: 'my-actions',
    label: 'My Actions',
    icon: ListTodo,
    href: 'my-actions',
    permission: PERMISSIONS.NAV_MY_ACTIONS,
    group: 'dashboard',
  },

  // COLLECTIONS LOG
  {
    id: 'collections',
    label: 'Collections Log',
    customIcon: sandwich_logo,
    href: 'collections',
    permission: PERMISSIONS.NAV_COLLECTIONS_LOG,
    group: 'collections',
  },

  // Move these back to their original groups without creating "core"

  // COMMUNICATION
  {
    id: 'chat',
    label: 'Team Chat',
    icon: Hash,
    href: 'chat',
    permission: PERMISSIONS.NAV_TEAM_CHAT,
    group: 'communication',
  },
  {
    id: 'gmail-inbox',
    label: 'Inbox',
    icon: Inbox,
    href: 'gmail-inbox',
    permission: PERMISSIONS.NAV_INBOX,
    group: 'communication',
  },
  {
    id: 'suggestions',
    label: 'Suggestions',
    icon: Lightbulb,
    href: 'suggestions',
    permission: PERMISSIONS.NAV_SUGGESTIONS,
    group: 'communication',
  },

  // OPERATIONS (the weekly flow)
  {
    id: 'hosts',
    label: 'Hosts',
    icon: Building2,
    href: 'hosts',
    permission: PERMISSIONS.NAV_HOSTS,
    group: 'operations',
  },
  {
    id: 'drivers',
    label: 'Drivers',
    icon: Car,
    href: 'drivers',
    permission: PERMISSIONS.NAV_DRIVERS,
    group: 'operations',
  },
  {
    id: 'volunteers',
    label: 'Volunteers',
    icon: Users,
    href: 'volunteers',
    permission: PERMISSIONS.NAV_VOLUNTEERS,
    group: 'operations',
  },
  {
    id: 'recipients',
    label: 'Recipients',
    icon: Users,
    href: 'recipients',
    permission: PERMISSIONS.NAV_RECIPIENTS,
    group: 'operations',
  },
  {
    id: 'groups-catalog',
    label: 'Groups Catalog',
    icon: Building,
    href: 'groups-catalog',
    permission: PERMISSIONS.NAV_GROUPS_CATALOG,
    group: 'operations',
  },
  {
    id: 'donation-tracking',
    label: 'Distribution Tracking',
    icon: Truck,
    href: 'donation-tracking',
    permission: PERMISSIONS.NAV_DISTRIBUTION_TRACKING,
    group: 'operations',
  },
  {
    id: 'inventory-calculator',
    label: 'Inventory Calculator',
    icon: Calculator,
    href: 'inventory-calculator',
    permission: PERMISSIONS.NAV_INVENTORY_CALCULATOR,
    group: 'operations',
  },
  {
    id: 'work-log',
    label: 'Work Log',
    icon: ClipboardList,
    href: 'work-log',
    permission: PERMISSIONS.NAV_WORK_LOG,
    group: 'operations',
  },

  // PLANNING & COORDINATION
  {
    id: 'events',
    label: 'Events Google Sheet',
    icon: Calendar,
    href: 'events',
    permission: PERMISSIONS.EVENT_REQUESTS_VIEW,
    group: 'planning',
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: ListTodo,
    href: 'projects',
    permission: PERMISSIONS.PROJECTS_VIEW,
    group: 'planning',
  },
  {
    id: 'meetings',
    label: 'Meetings',
    icon: ClipboardList,
    href: 'meetings',
    permission: PERMISSIONS.MEETINGS_VIEW,
    group: 'planning',
  },
  {
    id: 'event-requests',
    label: 'Event Planning',
    icon: Calendar,
    href: 'event-requests',
    permission: PERMISSIONS.EVENT_REQUESTS_VIEW,
    group: 'planning',
  },
  {
    id: 'event-reminders',
    label: 'Event Reminders',
    icon: Clock,
    href: 'event-reminders',
    permission: PERMISSIONS.EVENT_REQUESTS_VIEW,
    group: 'planning',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    icon: BarChart3,
    href: 'analytics',
    permission: PERMISSIONS.ANALYTICS_VIEW,
    group: 'planning',
  },
  {
    id: 'weekly-monitoring',
    label: 'Weekly Monitoring',
    icon: Clock,
    href: 'weekly-monitoring',
    permission: PERMISSIONS.NAV_WEEKLY_MONITORING,
    group: 'planning',
  },

  // DOCUMENTATION
  {
    id: 'important-documents',
    label: 'Important Documents',
    icon: FileText,
    href: 'important-documents',
    group: 'documentation',
  },
  {
    id: 'important-links',
    label: 'Important Links',
    icon: Link,
    href: 'important-links',
    group: 'documentation',
  },
  {
    id: 'toolkit',
    label: 'Toolkit',
    icon: FolderOpen,
    href: 'toolkit',
    permission: PERMISSIONS.NAV_TOOLKIT,
    group: 'documentation',
  },
  {
    id: 'document-management',
    label: 'Document Management',
    icon: FileText,
    href: 'document-management',
    permission: PERMISSIONS.NAV_DOCUMENT_MANAGEMENT,
    group: 'documentation',
  },

  // ADMIN
  {
    id: 'admin',
    label: 'Admin Panel',
    icon: Settings,
    href: 'admin',
    permission: PERMISSIONS.ADMIN_PANEL_ACCESS,
    group: 'admin',
  },
  {
    id: 'user-management',
    label: 'User Management',
    icon: UserCog,
    href: 'user-management',
    permission: PERMISSIONS.ADMIN_PANEL_ACCESS,
    group: 'admin',
  },
];