import {
  Sandwich,
  LayoutDashboard,
  ListTodo,
  MessageCircle,
  ClipboardList,
  FolderOpen,
  BarChart3,
  Users,
  Car,
  Building2,
  Building,
  FileText,
  Settings,
  Sheet,
  Lightbulb,
  Inbox,
  Hash,
  Scale,
  Calendar,
  MapPin,
  Route,
  Clock,
  Gift,
  Link,
  Calculator,
  Truck,
  UserCog,
  Trophy,
  FileSpreadsheet,
  Package,
  HelpCircle,
  StickyNote,
  Image,
  DollarSign,
  Receipt,
  Sparkles,
  Gauge,
  GitMerge,
  Zap,
  Target,
  HandHeart,
  Wrench,
  BookOpen,
} from 'lucide-react';
import { NavItem } from './nav.types';
import { PERMISSIONS } from '@shared/auth-utils';
import sandwich_logo from '@assets/LOGOS/sandwich logo.png';

export const NAV_ITEMS: NavItem[] = [
  // ========================================
  // DASHBOARD
  // ========================================
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    href: 'dashboard',
    group: 'dashboard',
  },

  // ========================================
  // QUICK LINKS (The "High Speed" Zone)
  // ========================================
  {
    id: 'collections',
    label: 'Collections Log',
    customIcon: sandwich_logo,
    href: 'collections',
    permission: PERMISSIONS.NAV_COLLECTIONS_LOG,
    group: 'quick-links',
    highlighted: true,
  },
  {
    id: 'events',
    label: 'Events Google Sheet',
    icon: Sheet,
    href: 'events',
    permission: PERMISSIONS.NAV_EVENTS_GOOGLE_SHEET,
    group: 'quick-links',
  },
  {
    id: 'signup-genius',
    label: 'SignUpGenius',
    icon: Link,
    href: 'signup-genius',
    permission: PERMISSIONS.NAV_SIGNUP_GENIUS,
    group: 'quick-links',
  },
  {
    id: 'quick-tools',
    label: 'Toolkit & Apps',
    icon: Wrench,
    href: 'important-links',
    // No permission - Toolkit & Apps is available to everyone
    group: 'quick-links',
    highlighted: true,
  },
  {
    id: 'resources',
    label: 'Reference Materials',
    icon: BookOpen,
    href: 'resources',
    permission: PERMISSIONS.NAV_RESOURCES,
    group: 'quick-links',
    highlighted: true,
  },
  {
    id: 'inventory-calculator',
    label: 'Inventory Calculator',
    icon: Calculator,
    href: 'inventory-calculator',
    permission: PERMISSIONS.NAV_INVENTORY_CALCULATOR,
    group: 'quick-links',
  },
  {
    id: 'wishlist',
    label: 'Wishlist Manager',
    icon: Gift,
    href: 'wishlist',
    permission: PERMISSIONS.NAV_WISHLIST,
    group: 'quick-links',
  },
  {
    id: 'quick-sms-links',
    label: 'Quick SMS Links',
    icon: MessageCircle,
    href: 'quick-sms-links',
    permission: PERMISSIONS.NAV_QUICK_SMS_LINKS,
    group: 'quick-links',
  },

  // ========================================
  // MY WORKSPACE (Daily Management)
  // ========================================
  {
    id: 'my-actions',
    label: 'My Actions',
    icon: ListTodo,
    href: 'my-actions',
    permission: PERMISSIONS.NAV_MY_ACTIONS,
    group: 'workspace',
  },
  {
    id: 'inbox-consolidated',
    label: 'Project Threads',
    icon: Inbox,
    href: 'gmail-inbox',
    permission: PERMISSIONS.NAV_INBOX,
    group: 'workspace',
  },
  {
    id: 'chat',
    label: 'Team Chat',
    icon: Hash,
    href: 'chat',
    permission: PERMISSIONS.NAV_TEAM_CHAT,
    group: 'workspace',
  },
  {
    id: 'kudos',
    label: 'Kudos',
    icon: Trophy,
    href: 'kudos',
    permission: PERMISSIONS.KUDOS_VIEW,
    group: 'workspace',
  },
  {
    id: 'team-board',
    label: 'Holding Zone',
    icon: StickyNote,
    href: 'team-board',
    permission: PERMISSIONS.VIEW_HOLDING_ZONE,
    group: 'workspace',
    highlighted: true,
  },
  {
    id: 'calendars',
    label: 'Calendars',
    icon: Calendar,
    href: 'calendars',
    permission: PERMISSIONS.NAV_YEARLY_CALENDAR,
    group: 'workspace',
    highlighted: true,
  },
  {
    id: 'yearly-calendar',
    label: 'TSP Yearly Calendar',
    icon: Calendar,
    href: 'yearly-calendar',
    permission: PERMISSIONS.NAV_YEARLY_CALENDAR,
    group: 'workspace',
    parentId: 'calendars',
    isSubItem: true,
  },
  {
    id: 'my-availability',
    label: 'My Availability',
    icon: Calendar,
    href: 'my-availability',
    permission: PERMISSIONS.NAV_MY_AVAILABILITY,
    group: 'workspace',
    parentId: 'calendars',
    isSubItem: true,
  },
  {
    id: 'team-availability',
    label: 'Team Availability',
    icon: Users,
    href: 'team-availability',
    permission: PERMISSIONS.NAV_TEAM_AVAILABILITY,
    group: 'workspace',
    parentId: 'calendars',
    isSubItem: true,
  },
  {
    id: 'google-calendar-availability',
    label: 'Volunteer Calendar',
    icon: Calendar,
    href: 'google-calendar-availability',
    permission: PERMISSIONS.NAV_VOLUNTEER_CALENDAR,
    group: 'workspace',
    parentId: 'calendars',
    isSubItem: true,
  },
  {
    id: 'promotion',
    label: 'Social Media Graphics',
    icon: Image,
    href: 'promotion',
    permission: PERMISSIONS.NAV_PROMOTION,
    group: 'workspace',
  },

  // ========================================
  // LOGISTICS (Event & Future Planning)
  // ========================================
  {
    id: 'event-requests',
    label: 'Event Requests',
    icon: Calendar,
    href: 'event-requests',
    permission: PERMISSIONS.NAV_EVENT_PLANNING,
    group: 'logistics',
    highlighted: true,
    navigateAndExpand: true,
  },
  {
    id: 'event-ops-dashboard',
    label: 'Ops Dashboard',
    icon: Gauge,
    href: 'event-ops-dashboard',
    permission: PERMISSIONS.NAV_EVENT_PLANNING,
    group: 'logistics',
    parentId: 'event-requests',
    isSubItem: true,
    highlighted: true,
  },
  {
    id: 'admin-overview',
    label: 'Admin Overview',
    icon: BarChart3,
    href: 'event-requests?tab=admin_overview',
    permission: PERMISSIONS.EVENT_REQUESTS_VIEW_ADMIN_OVERVIEW,
    group: 'logistics',
    parentId: 'event-requests',
    isSubItem: true,
  },
  {
    id: 'driver-planning',
    label: 'Driver Planning',
    icon: Truck,
    href: 'driver-planning',
    permission: PERMISSIONS.NAV_DRIVER_PLANNING,
    group: 'logistics',
    highlighted: true,
  },
  {
    id: 'volunteer-hub',
    label: 'Volunteer Hub',
    icon: HandHeart,
    href: 'volunteer-hub',
    permission: PERMISSIONS.NAV_VOLUNTEER_HUB,
    group: 'logistics',
    highlighted: true,
  },
  {
    id: 'host-resources',
    label: 'Host Resources',
    icon: Building2,
    href: 'host-resources',
    permission: PERMISSIONS.NAV_HOST_RESOURCES,
    group: 'logistics',
    highlighted: true,
  },
  {
    id: 'maps',
    label: 'Maps',
    icon: MapPin,
    href: 'event-map',
    permission: PERMISSIONS.NAV_MAPS,
    group: 'logistics',
  },
  {
    id: 'route-map',
    label: 'Locations Map',
    icon: MapPin,
    href: 'route-map',
    permission: PERMISSIONS.NAV_HOSTS,
    group: 'logistics',
    parentId: 'maps',
    isSubItem: true,
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: ListTodo,
    href: 'projects',
    permission: PERMISSIONS.NAV_PROJECTS,
    group: 'logistics',
  },
  {
    id: 'meetings',
    label: 'Meetings',
    icon: ClipboardList,
    href: 'meetings',
    permission: PERMISSIONS.NAV_MEETINGS,
    group: 'logistics',
    highlighted: true,
  },

  // ========================================
  // NETWORK (People Database)
  // ========================================
  {
    id: 'directory',
    label: 'Directory',
    icon: Users,
    href: 'directory',
    // No permission - parent shows for everyone, children control their own visibility
    group: 'network',
    highlighted: true,
  },
  {
    id: 'volunteers',
    label: 'Volunteers',
    icon: Users,
    href: 'volunteers',
    permission: PERMISSIONS.NAV_VOLUNTEERS,
    group: 'network',
    parentId: 'directory',
    isSubItem: true,
  },
  {
    id: 'drivers',
    label: 'Drivers',
    icon: Car,
    href: 'drivers',
    permission: PERMISSIONS.NAV_DRIVERS,
    group: 'network',
    parentId: 'directory',
    isSubItem: true,
  },
  {
    id: 'hosts',
    label: 'Hosts',
    icon: Building2,
    href: 'hosts',
    permission: PERMISSIONS.NAV_HOSTS,
    group: 'network',
    parentId: 'directory',
    isSubItem: true,
  },
  {
    id: 'partners',
    label: 'Partners',
    icon: Building,
    href: 'partners',
    // No permission - parent shows for everyone, children control their own visibility
    group: 'network',
    highlighted: true,
  },
  {
    id: 'recipients',
    label: 'Recipients',
    icon: Users,
    href: 'recipients',
    permission: PERMISSIONS.NAV_RECIPIENTS,
    group: 'network',
    parentId: 'partners',
    isSubItem: true,
  },
  {
    id: 'groups-catalog',
    label: 'Groups Catalog',
    icon: Building,
    href: 'groups-catalog',
    permission: PERMISSIONS.NAV_GROUPS_CATALOG,
    group: 'network',
    parentId: 'partners',
    isSubItem: true,
  },
  {
    id: 'groups-insights',
    label: 'Groups Engagement Insights',
    icon: Sparkles,
    href: 'groups-insights',
    permission: PERMISSIONS.NAV_GROUPS_CATALOG,
    group: 'network',
    parentId: 'partners',
    isSubItem: true,
    highlighted: true,
  },
  {
    id: 'event-contacts-directory',
    label: 'Event Contacts',
    icon: Users,
    href: 'event-contacts-directory',
    permission: PERMISSIONS.NAV_HOSTS,
    group: 'network',
    parentId: 'partners',
    isSubItem: true,
  },

  // ========================================
  // OPERATIONS (Tracking The Work)
  // ========================================
  {
    id: 'collections-reporting',
    label: 'Collections Analysis',
    icon: FileSpreadsheet,
    href: 'weekly-collections-report',
    permission: PERMISSIONS.NAV_COLLECTIONS_REPORTING,
    group: 'operations',
  },
  {
    id: 'weekly-collections-report',
    label: 'Weekly Collections Report',
    icon: FileSpreadsheet,
    href: 'weekly-collections-report',
    permission: PERMISSIONS.NAV_WEEKLY_COLLECTIONS_REPORT,
    group: 'operations',
    parentId: 'collections-reporting',
    isSubItem: true,
  },
  {
    id: 'group-collections',
    label: 'Group Collections Viewer',
    icon: Users,
    href: 'group-collections',
    permission: PERMISSIONS.NAV_GROUP_COLLECTIONS,
    group: 'operations',
    parentId: 'collections-reporting',
    isSubItem: true,
  },
  {
    id: 'donation-tracking',
    label: 'Distribution Tracking',
    icon: Truck,
    href: 'donation-tracking',
    permission: PERMISSIONS.NAV_DISTRIBUTION_TRACKING,
    group: 'operations',
  },
  {
    id: 'cooler-tracking',
    label: 'Cooler Tracking',
    icon: Package,
    href: 'cooler-tracking',
    permission: PERMISSIONS.NAV_COOLER_TRACKING,
    group: 'operations',
  },
  {
    id: 'work-log',
    label: 'Work Log',
    icon: ClipboardList,
    href: 'work-log',
    permission: PERMISSIONS.NAV_WORK_LOG,
    group: 'operations',
  },
  {
    id: 'expenses',
    label: 'Expenses & Receipts',
    icon: Receipt,
    href: 'expenses',
    permission: PERMISSIONS.NAV_EXPENSES,
    group: 'operations',
    highlighted: true,
  },

  // ========================================
  // ADMIN & RESOURCES
  // ========================================
  {
    id: 'analytics-section',
    label: 'Analytics & Reports',
    icon: BarChart3,
    href: 'analytics',
    permission: PERMISSIONS.NAV_ANALYTICS,
    group: 'admin',
    highlighted: true,
  },
  {
    id: 'analytics',
    label: 'Analytics Dashboard',
    icon: BarChart3,
    href: 'analytics',
    permission: PERMISSIONS.NAV_ANALYTICS,
    group: 'admin',
    parentId: 'analytics-section',
    isSubItem: true,
  },
  {
    id: 'grant-metrics',
    label: 'Grant Metrics',
    icon: Trophy,
    href: 'grant-metrics',
    permission: PERMISSIONS.NAV_GRANT_METRICS,
    group: 'admin',
    parentId: 'analytics-section',
    isSubItem: true,
  },
  {
    id: 'weekly-monitoring',
    label: 'Weekly Monitoring',
    icon: Clock,
    href: 'weekly-monitoring',
    permission: PERMISSIONS.NAV_WEEKLY_MONITORING,
    group: 'admin',
    parentId: 'analytics-section',
    isSubItem: true,
  },
  {
    id: 'event-impact-reports',
    label: 'Event Impact Reports',
    icon: BarChart3,
    href: 'event-impact-reports',
    permission: PERMISSIONS.NAV_EVENT_IMPACT_REPORTS,
    group: 'admin',
    parentId: 'analytics-section',
    isSubItem: true,
  },
  {
    id: 'tools',
    label: 'Tools',
    icon: Zap,
    href: 'smart-search-admin', // Default to first tool item
    permission: PERMISSIONS.NAV_TOOLS,
    group: 'admin',
  },
  {
    id: 'smart-search-admin',
    label: 'SmartSearch AI',
    icon: Sparkles,
    href: 'smart-search-admin',
    permission: PERMISSIONS.NAV_SMART_SEARCH_ADMIN,
    group: 'admin',
    parentId: 'tools',
    isSubItem: true,
  },
  {
    id: 'generate-service-hours',
    label: 'Service Hours Form',
    icon: FileText,
    href: 'generate-service-hours',
    permission: PERMISSIONS.NAV_SERVICE_HOURS_FORM,
    group: 'admin',
    parentId: 'tools',
    isSubItem: true,
  },
  // Quick Tools and Reference Materials moved to quick-links group (after SignUpGenius)
  {
    id: 'documents',
    label: 'Documents',
    icon: FileText,
    href: 'document-management',
    permission: PERMISSIONS.NAV_DOCUMENTS,
    group: 'admin',
  },
  {
    id: 'document-management',
    label: 'Document Management',
    icon: FileText,
    href: 'document-management',
    permission: PERMISSIONS.NAV_DOCUMENT_MANAGEMENT,
    group: 'admin',
    parentId: 'documents',
    isSubItem: true,
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    href: 'admin',
    permission: PERMISSIONS.ADMIN_PANEL_ACCESS,
    group: 'admin',
  },
  {
    id: 'admin',
    label: 'Admin Panel',
    icon: Settings,
    href: 'admin',
    permission: PERMISSIONS.ADMIN_PANEL_ACCESS,
    group: 'admin',
    parentId: 'settings',
    isSubItem: true,
  },
  {
    id: 'user-management',
    label: 'User Management',
    icon: UserCog,
    href: 'user-management',
    permission: PERMISSIONS.NAV_USER_MANAGEMENT,
    group: 'admin',
    parentId: 'settings',
    isSubItem: true,
  },
  {
    id: 'historical-import',
    label: 'Historical Import',
    icon: FileSpreadsheet,
    href: 'historical-import',
    permission: PERMISSIONS.NAV_HISTORICAL_IMPORT,
    group: 'admin',
    parentId: 'settings',
    isSubItem: true,
  },
  {
    id: 'organizations-merge',
    label: 'Merge Organizations',
    icon: GitMerge,
    href: 'organizations-merge',
    permission: PERMISSIONS.ADMIN_PANEL_ACCESS,
    group: 'admin',
    parentId: 'settings',
    isSubItem: true,
  },

  // ========================================
  // TOP NAV ITEMS
  // ========================================
  {
    id: 'help',
    label: 'Help',
    icon: HelpCircle,
    href: 'help',
    permission: PERMISSIONS.NAV_HELP,
    group: 'help',
    topNav: true,
  },
  {
    id: 'suggestions',
    label: 'Suggestions',
    icon: Lightbulb,
    href: 'suggestions',
    permission: PERMISSIONS.NAV_SUGGESTIONS,
    group: 'communication',
    topNav: true,
  },
];
