DELETE FROM hosts;
INSERT INTO hosts (id, name, contact_person, phone, email, address, notes, is_active, created_at, updated_at) VALUES
('55', 'Alpharetta, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('63', 'Buckhead, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('36', 'Buckhead, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('42', 'Chamblee/N Brookhaven, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('53', 'Collective Learning, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('46', 'College Park, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('48', 'Dacula, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('29', 'Decatur, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('56', 'Dunwoody/PTC, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('57', 'East Cobb/Roswell, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('60', 'Flowery Branch, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('35', 'Glenwood Park, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('62', 'Groups, NULL, NULL, NULL, 'Multiple Locations, 'Special host for group donations that don''t have a specific host location. These are collective donations from various groups., true, NOW(), NOW()),
('59', 'Intown/Druid Hills/Oak Grove/Chamblee/Brookhaven/Buckhead, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('34', 'Lenox/Brookhaven, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('43', 'Lilburn, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('33', 'New Chastain, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('32', 'Oak Grove, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('45', 'Peachtree Corners, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('65', 'Peachtree Corners, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('38', 'Roswell, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('58', 'Sandy Springs/Chastain, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('30', 'Snellville, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('64', 'Snellville, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('50', 'Suwanee/JC/Duluth, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('54', 'UGA, NULL, NULL, NULL, 'Athens, NULL, true, NOW(), NOW()),
('31', 'Woodstock, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW()),
('66', 'Woodstock, NULL, NULL, NULL, NULL, NULL, true, NOW(), NOW());